"""user add note

Revision ID: 872c416c5045
Revises: fbb57a57f161
Create Date: 2022-05-08 13:47:24.218956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872c416c5045'
down_revision = 'fbb57a57f161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('note', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'note')
    # ### end Alembic commands ###
